EMPTY_API_EVENT = {
    "resource": "/logs",
    "path": "/logs",
    "httpMethod": "GET",
    "headers": None,
    "multiValueHeaders": None,
    "queryStringParameters": None,
    "multiValueQueryStringParameters": None,
    "pathParameters": None,
    "stageVariables": None,
    "requestContext": {
        "resourceId": "90f2uo",
        "resourcePath": "/logs",
        "httpMethod": "GET",
        "extendedRequestId": "C9zFeGUuliAFVnQ=",
        "requestTime": "06/Apr/2023:17:18:39 +0000",
        "path": "/logs",
        "accountId": "886303093546",
        "protocol": "HTTP/1.1",
        "stage": "test-invoke-stage",
        "domainPrefix": "testPrefix",
        "requestTimeEpoch": 1680801519542,
        "requestId": "2caff4cd-0632-48ee-a65a-3f9c9232e2fe",
        "identity": {
            "cognitoIdentityPoolId": None,
            "cognitoIdentityId": None,
            "apiKey": "test-invoke-api-key",
            "principalOrgId": None,
            "cognitoAuthenticationType": None,
            "userArn": "arn:aws:iam::886303093546:root",
            "apiKeyId": "test-invoke-api-key-id",
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62",
            "accountId": "886303093546",
            "caller": "886303093546",
            "sourceIp": "test-invoke-source-ip",
            "accessKey": "ASIA44W6H6MVBVKHVAA4",
            "cognitoAuthenticationProvider": None,
            "user": "886303093546",
        },
        "domainName": "testPrefix.testDomainName",
        "apiId": "yln1qwzolk",
    },
    "body": None,
    "isBase64Encoded": False,
}
