openapi: 3.0.1
info:
  description: CLoudLog api definition
  version: "1.0.3"
  title: CloudLog
  contact:
    email: szymonrykala@gmail.com

security:
  - AWS_IAM: []

paths:
  /logs:
    get:
      tags:
        - logs
      parameters:
        - $ref: "#/components/parameters/fromTime"
        - $ref: "#/components/parameters/toTime"
        - $ref: "#/components/parameters/hostname"
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/service"
        - $ref: "#/components/parameters/severity"
      x-amazon-apigateway-request-validator: full-request-validation
      x-amazon-apigateway-integration:
        credentials: ${gateway_iam_role}
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        passthroughBehavior": when_no_templates
        type: "AWS_PROXY"
        uri: arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${get_logs_arn}/invocations

      responses:
        "200":
          description: users list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DBLogItem"
        "400":
          description: request data are not correct
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: explonation of the error

    put:
      tags:
        - logs
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/LogItem"
      x-amazon-apigateway-request-validator: full-request-validation
      x-amazon-apigateway-integration:
        type: AWS
        httpMethod: POST
        uri: arn:aws:apigateway:${region}:sqs:path/${account_id}/${logs_buffer_queue_name}
        credentials: ${gateway_iam_role}
        contentHandling: CONVERT_TO_TEXT
        passthroughBehavior: "never"
        requestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
        requestTemplates:
          application/json: "Action=SendMessage&MessageBody=$input.body"
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: >
                { "message": "message sent" }

      responses:
        "200":
          description: logs sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


x-amazon-apigateway-request-validators:
  "full-request-validation":
    validateRequestParameters: true
    validateRequestBody: true

components:
  securitySchemes:
    AWS_IAM:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: awsSigv4

  parameters:
    fromTime:
      in: query
      name: fromDate
      description: datetime to search from
      required: False
      schema:
        type: string
        format: date-time
        example: 2023-04-15T10:00:00

    toTime:
      in: query
      name: toDate
      description: end datetime to search to
      required: False
      schema:
        type: string
        format: date-time
        example: 2023-04-20T10:00:00

    type:
      in: query
      name: type
      description: type of log
      required: False
      schema:
        type: string
        enum: [system, application, logger]
        example: user

    service:
      in: query
      name: service
      description: service, app that logged
      required: False
      schema:
        type: string
        example: windows-update

    hostname:
      in: query
      name: hostname
      description: log host machine
      required: False
      schema:
        type: string
        example: lenovo-xyz900

    severity:
      in: query
      name: severity
      description: lowest log severity
      required: False
      schema:
        type: integer
        minimum: 0
        maximum: 7
        example: 1

  schemas:
    DBLogItem:
      allOf:
        - type: object
          properties:
            id:
              type: string
              format: uuid
              example: eb573694-dc48-11ed-b719-3b8ae20b0d00
        - $ref: "#/components/schemas/LogItem"

    LogItem:
      type: object
      properties:
        os:
          type: string
          enum: [windows, linux]
        timestamp:
          type: number
          example: 1675557738.587889
        severity:
          type: integer
          minimum: 0
          maximum: 7
          example: 1
        message:
          type: string
          example: "Fontconfig error: \"/etc/fonts/conf.d/80-delicious.conf\", line 6: invalid attribute 'version'"
        type:
          type: string
          enum: [application, system, logger]
          example: Application
        hostname:
          type: string
          example: user-laptop
        raw:
          type: string
          example: "kwi 16 13:11:42 szymon-latitude postman_postman.desktop[9226]: Fontconfig error: \"/etc/fonts/conf.d/80-delicious.conf\", line 6: invalid attribute 'version'"
        unit:
          type: string
          example: /snap/postman/184/usr/share/postman

  responses:
    LogsResponse:
      description: successfull response with array of logs
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/LogItem"

    UnauthorizedError:
      description: Access token is missing or invalid
